version: '3.3'

services:

  redis:
    image: redis
    restart: always
    container_name: my-redis
    ports:
      - 6379:6379
    network_mode: "host"

  chat-message:
    container_name: chat-message
    build: .
    ports:
      - 10091:10091
    network_mode: "host"
