version: '3.1'

services:

  redis:
    image: redis
    restart: always
    container_name: my-redis
    ports:
      - 6379:6379

  active-mq:
    image: webcenter/activemq
    restart: always
    container_name: my-active-mq
    ports:
      - 61616:61616
      - 8161:8161
    environment:
      - ACTIVEMQ_CONFIG_MINMEMORY=512
      - ACTIVEMQ_CONFIG_MAXMEMORY=2048
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin